on:
  push:
    branches:
      - master
  schedule:
      - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  cpe:
    runs-on: ubuntu-latest
    steps:
      - name: checkout fleet
        uses: actions/checkout@v2
        with:
          repository: fleetdm/fleet
          fetch-depth: 1
          ref: main
          token: ${{ github.token }}
      - name: run generate
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.4'
      - name: generate cpe sqlite
        run: go mod download && go run -tags full,fts5 cmd/cpe/generate.go
      - name: Set env
        if: hashFiles('*.sqlite.gz') != ''
        run: cat ./etagenv >> $GITHUB_ENV
      - name: Tag
        if: hashFiles('*.sqlite.gz') != ''
        run: git tag ${{ env.ETAG }}
      - name: release
        if: hashFiles('*.sqlite.gz') != ''
        uses: softprops/action-gh-release@v1
        with:
          files: "*.sqlite.gz"
          tag_name: ${{ env.ETAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
